# Generated by Django 6.1.1 on 2026-09-17 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sotuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('tolandi', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="To'landi")),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('yakunlangan', models.BooleanField(default=False, verbose_name='Yakunlangan')),
            ],
            options={
                'verbose_name': 'Sotuv',
                'verbose_name_plural': 'Sotuvlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='SotuvQator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=120, verbose_name='Tovar nomi')),
                ('birlik', models.CharField(blank=True, max_length=10, verbose_name='Birlik')),
                ('miqdor', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sotuv_qatorlari', to='ombor.mahsulot')),
                ('sotuv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='sotuv.sotuv')),
            ],
            options={
                'verbose_name': 'Sotuv qatori',
                'verbose_name_plural': 'Sotuv qatorlari',
                'ordering': ['id'],
            },
        ),
    ]
