# Generated by Django 6.1.1 on 2026-09-22 06:31

"""Chekda ikkita alohida jami: so'm va dollar, ustiga o'sha kungi kurs."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0002_jami_qolda'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuv',
            name='jami_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami dollar'),
        ),
        migrations.AddField(
            model_name='sotuv',
            name='kurs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dollar kursi'),
        ),
        migrations.AlterField(
            model_name='sotuv',
            name='jami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Jami so'm"),
        ),
    ]
