# Generated by Django 6.1.1 on 2026-09-22 06:45

"""Sotuv o'chirilmaydi (bekor qilinadi) va qaytarib berish yozib boriladi."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sotuv', '0003_valyuta_ajratildi'),
    ]

    operations = [
        migrations.AddField(
            model_name='sotuv',
            name='bekor_qilingan',
            field=models.BooleanField(default=False, verbose_name='Bekor qilingan'),
        ),
        migrations.AddField(
            model_name='sotuv',
            name='qaytarilgan_summa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Qaytarilgan so'm"),
        ),
        migrations.AddField(
            model_name='sotuv',
            name='qaytarilgan_summa_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Qaytarilgan dollar'),
        ),
        migrations.AddField(
            model_name='sotuvqator',
            name='qaytarilgan',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qaytarilgan miqdor'),
        ),
    ]
