# Generated by Django 6.1.1 on 2026-09-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120, unique=True, verbose_name='Nomi')),
                ('birlik', models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('metr', 'metr'), ('litr', 'litr'), ('qop', 'qop'), ('quti', 'quti')], default='dona', max_length=10, verbose_name='Birlik')),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Narxi')),
                ('qoldiq', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qoldiq')),
                ('faol', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='OmborHarakati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('tuzatish', 'Tuzatish')], max_length=10, verbose_name='Turi')),
                ('miqdor', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='harakatlar', to='ombor.mahsulot')),
            ],
            options={
                'verbose_name': 'Ombor harakati',
                'verbose_name_plural': 'Ombor harakatlari',
                'ordering': ['-sana'],
            },
        ),
    ]
