# Generated by Django 6.1.1 on 2026-09-18 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='olish_birligi',
            field=models.CharField(blank=True, choices=[('dona', 'dona'), ('kg', 'kg'), ('metr', 'metr'), ('litr', 'litr'), ('qop', 'qop'), ('quti', 'quti'), ('rulon', 'rulon'), ('buxta', 'buxta'), ('pachka', 'pachka'), ('list', 'list'), ('tonna', 'tonna')], default='', help_text="Tovar boshqa birlikda olinsa tanlang. Bo'sh bo'lsa — sotuv birligining o'zi.", max_length=10, verbose_name='Olish birligi'),
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='olish_miqdori',
            field=models.DecimalField(decimal_places=3, default=1, help_text='1 olish birligida nechta sotuv birligi bor. Masalan 1 rulon = 100 metr.', max_digits=12, verbose_name='Bittasida'),
        ),
        migrations.AddField(
            model_name='omborharakati',
            name='kiritilgan_birlik',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kiritilgan birlik'),
        ),
        migrations.AddField(
            model_name='omborharakati',
            name='kiritilgan_miqdor',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Kiritilgan miqdor'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='birlik',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('metr', 'metr'), ('litr', 'litr'), ('qop', 'qop'), ('quti', 'quti'), ('rulon', 'rulon'), ('buxta', 'buxta'), ('pachka', 'pachka'), ('list', 'list'), ('tonna', 'tonna')], default='dona', max_length=10, verbose_name='Sotuv birligi'),
        ),
    ]
