# Generated by Django 6.1.1 on 2026-09-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0002_mahsulot_olish_birligi_mahsulot_olish_miqdori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='nom',
            field=models.CharField(error_messages={'unique': 'Bunday nomli tovar allaqachon bor.'}, max_length=120, unique=True, verbose_name='Nomi'),
        ),
    ]
