# Generated by Django 6.1.1 on 2026-09-18 07:04

from django.db import migrations, models

# Birlik nomi mahsulot, ombor harakati, qarz qatori va sotuv qatorida
# matn bo'lib yotadi — hammasini birga ko'chiramiz.
MAYDONLAR = [
    ("ombor", "Mahsulot", ["birlik", "olish_birligi"]),
    ("ombor", "OmborHarakati", ["kiritilgan_birlik"]),
    ("qarz", "QarzQator", ["birlik"]),
    ("sotuv", "SotuvQator", ["birlik"]),
]


def _almashtir(apps, eski, yangi):
    for ilova, model, maydonlar in MAYDONLAR:
        Model = apps.get_model(ilova, model)
        for maydon in maydonlar:
            Model.objects.filter(**{maydon: eski}).update(**{maydon: yangi})


def buxtadan_oramga(apps, schema_editor):
    """«buxta» ruscha (бухта) — o'zbekchasi «o'ram»."""
    _almashtir(apps, "buxta", "o'ram")


def oramdan_buxtaga(apps, schema_editor):
    _almashtir(apps, "o'ram", "buxta")


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0003_alter_mahsulot_nom'),
        ('qarz', '0001_initial'),
        ('sotuv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='birlik',
            field=models.CharField(choices=[('dona', 'dona'), ('kg', 'kg'), ('metr', 'metr'), ('litr', 'litr'), ('qop', 'qop'), ('quti', 'quti'), ('rulon', 'rulon'), ("o'ram", "o'ram"), ('pachka', 'pachka'), ('list', 'list'), ('tonna', 'tonna')], default='dona', max_length=10, verbose_name='Sotuv birligi'),
        ),
        migrations.AlterField(
            model_name='mahsulot',
            name='olish_birligi',
            field=models.CharField(blank=True, choices=[('dona', 'dona'), ('kg', 'kg'), ('metr', 'metr'), ('litr', 'litr'), ('qop', 'qop'), ('quti', 'quti'), ('rulon', 'rulon'), ("o'ram", "o'ram"), ('pachka', 'pachka'), ('list', 'list'), ('tonna', 'tonna')], default='', help_text="Tovar boshqa birlikda olinsa tanlang. Bo'sh bo'lsa — sotuv birligining o'zi.", max_length=10, verbose_name='Olish birligi'),
        ),
        migrations.RunPython(buxtadan_oramga, oramdan_buxtaga),
    ]
