# Generated by Django 6.1.1 on 2026-09-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0004_alter_mahsulot_birlik_alter_mahsulot_olish_birligi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mahsulot',
            name='narx',
        ),
    ]
