# Generated by Django 6.1.1 on 2026-09-22 06:31

"""Tovar so'mda keldimi yoki dollardami — tovar qo'shishda so'raladi."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0005_remove_mahsulot_narx'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='valyuta',
            field=models.CharField(choices=[('som', "so'm"), ('dollar', 'dollar')], default='som', help_text="Tovar dollarda kelgan bo'lsa narxi ham dollarda hisoblanadi.", max_length=10, verbose_name='Qaysi pulda keladi'),
        ),
    ]
