# Generated by Django 6.1.1 on 2026-09-22 06:45

"""Ombor tarixida qaytarish alohida tur bo'lib ko'rinadi."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0006_tovar_valyutasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='omborharakati',
            name='tur',
            field=models.CharField(choices=[('kirim', 'Kirim'), ('chiqim', 'Chiqim'), ('qaytarish', 'Qaytarish'), ('tuzatish', 'Tuzatish')], max_length=10, verbose_name='Turi'),
        ),
    ]
