# Generated by Django 6.1.1 on 2026-09-22 07:01

"""Tovar kartochkasiga narx qaytdi — ma'lumot uchun (keyin elektron tarozi)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0007_qaytarish_harakati'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='narx',
            field=models.DecimalField(decimal_places=2, default=0, help_text="1 sotuv birligi uchun, tovarning valyutasida. Kassada summa baribir qo'lda yoziladi — bu narx ma'lumot uchun.", max_digits=12, verbose_name='Narxi'),
        ),
    ]
