# Generated by Django 6.1.1 on 2026-09-22 07:39

"""Markaziy bankdan olingan kun kursi bazada saqlanadi."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ombor', '0008_tovar_narxi'),
    ]

    operations = [
        migrations.CreateModel(
            name='DollarKursi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateField(unique=True, verbose_name='Sana')),
                ('kurs', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Kurs')),
                ('urinish', models.DateTimeField(auto_now=True, verbose_name='Oxirgi urinish')),
            ],
            options={
                'verbose_name': 'Dollar kursi',
                'verbose_name_plural': 'Dollar kurslari',
                'ordering': ['-sana'],
            },
        ),
    ]
