# Generated by Django 6.1.1 on 2026-09-17 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ombor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Hudud nomi')),
                ('tartib', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
            ],
            options={
                'verbose_name': 'Hudud',
                'verbose_name_plural': 'Hududlar',
                'ordering': ['tartib', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Qarzdor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=60, verbose_name='Ism')),
                ('familiya', models.CharField(max_length=60, verbose_name='Familiya')),
                ('telefon', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qarzdorlar', to='qarz.hudud', verbose_name='Hudud')),
            ],
            options={
                'verbose_name': 'Qarzdor',
                'verbose_name_plural': 'Qarzdorlar',
                'ordering': ['familiya', 'ism'],
            },
        ),
        migrations.CreateModel(
            name='Qarz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('yakunlangan', models.BooleanField(default=False, verbose_name='Yakunlangan')),
                ('qarzdor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qarzlar', to='qarz.qarzdor')),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='QarzQator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=120, verbose_name='Tovar nomi')),
                ('birlik', models.CharField(blank=True, max_length=10, verbose_name='Birlik')),
                ('miqdor', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Miqdor')),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Narxi')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qarz_qatorlari', to='ombor.mahsulot')),
                ('qarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='qarz.qarz')),
            ],
            options={
                'verbose_name': 'Qarz qatori',
                'verbose_name_plural': 'Qarz qatorlari',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tolov',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summa', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Summa')),
                ('sana', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('izoh', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('qarzdor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolovlar', to='qarz.qarzdor')),
            ],
            options={
                'verbose_name': "To'lov",
                'verbose_name_plural': "To'lovlar",
                'ordering': ['-sana'],
            },
        ),
    ]
