# Generated by Django 6.1.1 on 2026-09-22 06:31

"""Qarz va to'lov valyutasi ajratildi: so'm va dollar qo'shilib ketmaydi."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0002_jami_qolda'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarz',
            name='jami_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami dollar'),
        ),
        migrations.AddField(
            model_name='qarz',
            name='kurs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Dollar kursi'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='valyuta',
            field=models.CharField(choices=[('som', "so'm"), ('dollar', 'dollar')], default='som', max_length=10, verbose_name='Valyuta'),
        ),
        migrations.AlterField(
            model_name='qarz',
            name='jami',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name="Jami so'm"),
        ),
    ]
