# Generated by Django 6.1.1 on 2026-09-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qarz', '0004_qaytarib_berish'),
        ('sotuv', '0004_qaytarib_berish'),
    ]

    operations = [
        migrations.AddField(
            model_name='qarz',
            name='sotuv',
            field=models.OneToOneField(blank=True, help_text='Naqd sotuvda pul yetmay qolgan qismi shu yerga yoziladi.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qarz', to='sotuv.sotuv', verbose_name='Qaysi chekdan'),
        ),
        migrations.AddField(
            model_name='tolov',
            name='qarz',
            field=models.ForeignKey(blank=True, help_text="Qarz yozilayotganda darrov to'langan bo'lsa shu hujjat.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tolovlar', to='qarz.qarz', verbose_name='Qaysi hujjatga'),
        ),
    ]
